---

- name: H002-Ansible with inventory
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: sandbox_switches
  tasks:
    - name: Get config for IOS-XE devices
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Apply the hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "DEMO-{{ inventory_hostname }}"
        state: merged