---
- name:  H004-Variables and config
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Fetch variables from datamodel
      include_vars: ./dm.yml
      
    - name: Gather information as structured data
      cisco.ios.ios_facts:
        gather_subset: 
          - '!all'
          - min

    - name: Display the hostname and OS
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Apply configuration from DM 
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
        state: merged
      loop: "{{ dm[ansible_net_hostname].config_interfaces }}"
      when:
        - 'golden_os in ansible_net_version'