name: Pipeline Merge
run-name: Pipeline Merge (apply) - Ansible

on: 
  push:
    branches:
      - main
    paths:
      - "ansible-git-pipeline/**"
  
jobs:
  generate_ansible_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          repository: DEVKOM-AS/git-ansible-001
          sparse-checkout: |
            ansible-git-pipeline

      - name: Prepare environment (Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ansible-git-pipeline/requirements.txt

      # - name: Super-linter
      #   uses: super-linter/super-linter@v6.5.1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      - name: Running ansible in diff mode
        id: diff-run
        working-directory: ansible-git-pipeline
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook playbook.yml -i inventory.yml --extra-vars "ansible_password=${{ secrets.ANSIBLE_PWD }}" 2>&1 | tee ansible_apply.txt
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "diff<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat ansible_apply.txt)." >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      # Add diff result as comment
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### Diff result 
            ```
            ${{steps.diff-run.outputs.diff}}
            ```
            ### End diff result
          repo-token: ${{ github.token }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default